# Generated by Django 5.0.7 on 2024-10-05 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DeepMedApp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="medical_images/"),
        ),
    ]
